# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5a4d37774515353f3de3d558a42724299c2c4669c2d56881c5d1a7cabe2bd780021f47b2c349db91e6435049ef20487dd02cd4fb6a72da965f63f6017db338e

test:
  secret_key_base: a3d4b4604165706046a53e0094438d5e55861e9e85fa57192c140f82dfe042ceb745f97c02a733554a73224e4d0eb47a4b6ac754959d78a8af49090bc04f91c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
